### ISSUE TITLE
在IDEA中运行报错

### ISSUE THREAD

**Issue by qiuqingyu** [harbby/sylph#118]
19-09-23 09:20:34 ERROR[main][SylphMaster.java:83]-SERVER START FAILED...
java.lang.NoClassDefFoundError: org/apache/hadoop/yarn/conf/YarnConfiguration
	at ideal.sylph.runtime.yarn.YarnModule.configure(YarnModule.java:42)
	at com.github.harbby.gadtry.ioc.BindMapping.create(BindMapping.java:163)
	at com.github.harbby.gadtry.ioc.BindMapping.create(BindMapping.java:92)
	at com.github.harbby.gadtry.ioc.IocFactory.create(IocFactory.java:55)
	at ideal.sylph.runner.flink.FlinkContainerFactory.<init>(FlinkContainerFactory.java:67)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at ideal.sylph.main.service.JobEngineManager.lambda$createRunner$1(JobEngineManager.java:117)
	at com.github.harbby.gadtry.base.Throwables.noCatch(Throwables.java:94)
	at ideal.sylph.main.service.JobEngineManager.createRunner(JobEngineManager.java:117)
	at ideal.sylph.main.service.JobEngineManager.lambda$loadRunners$0(JobEngineManager.java:103)
	at com.github.harbby.gadtry.classloader.PluginLoader$Builder.loadModule(PluginLoader.java:205)
	at com.github.harbby.gadtry.classloader.PluginLoader$Builder.load(PluginLoader.java:189)
	at ideal.sylph.main.service.JobEngineManager.loadRunners(JobEngineManager.java:106)
	at ideal.sylph.main.SylphMaster.main(SylphMaster.java:73)
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.yarn.conf.YarnConfiguration
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at com.github.harbby.gadtry.classloader.PluginClassLoader.loadClass(PluginClassLoader.java:83)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 18 common frames omitted

**Comment by dylenWu** [comment]
应该是没有设置HADOOP_HOME
