### ISSUE TITLE
flink_1.9分支运行任务报错

### ISSUE THREAD

**Issue by shaoyou520** [harbby/sylph#156]
com.github.harbby.gadtry.jvm.JVMException: ForKJVMError: org.apache.flink.runtime.client.JobExecutionException: Job execution failed.
	at org.apache.flink.runtime.jobmaster.JobResult.toJobExecutionResult(JobResult.java:146)
	at org.apache.flink.runtime.minicluster.MiniCluster.executeJobBlocking(MiniCluster.java:627)
	at ideal.sylph.runner.flink.local.MiniExecutor.executeJobBlocking(MiniExecutor.java:88)
	at ideal.sylph.runner.flink.local.MiniExecutor.lambda$createVmCallable$9b2e45cb$1(MiniExecutor.java:111)
	at com.github.harbby.gadtry.jvm.JVMLauncher.main(JVMLauncher.java:58)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class ideal.sylph.plugins.kafka.flink.JsonDeserializer
	at java.io.ObjectStreamClass.hasStaticInitializer(Native Method)
	at java.io.ObjectStreamClass.computeDefaultSUID(ObjectStreamClass.java:1941)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class ideal.sylph.plugins.kafka.flink.JsonDeserializer

	at java.io.ObjectStreamClass.access$100(ObjectStreamClass.java:79)
	at java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:275)
	at java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:273)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.io.ObjectStreamClass.getSerialVersionUID(ObjectStreamClass.java:272)
	at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:694)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1885)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1751)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2042)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
	at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:576)
	at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:562)
	at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:550)
	at org.apache.flink.util.InstantiationUtil.readObjectFromConfig(InstantiationUtil.java:511)
	at org.apache.flink.streaming.api.graph.StreamConfig.getStreamOperatorFactory(StreamConfig.java:235)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.<init>(OperatorChain.java:115)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:370)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:705)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:530)
	at java.lang.Thread.run(Thread.java:748)

	at com.github.harbby.gadtry.jvm.VmResult.get(VmResult.java:31)
	at com.github.harbby.gadtry.jvm.VmFuture.get(VmFuture.java:88)
	at ideal.sylph.runtime.local.LocalContainer.getStatus(LocalContainer.java:91)
	at ideal.sylph.main.service.JobManager.lambda$null$0(JobManager.java:75)
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
	at ideal.sylph.main.service.JobManager.lambda$new$1(JobManager.java:74)
	at java.lang.Thread.run(Thread.java:748)
20-08-19 17:16:43 WARN[job_monitor][JobManager.java:77]-Job 13[24196] state is STOP, Will resubmit

**Comment by harbby** [comment]
fix #157
