### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/hadoop/yarn/conf/YarnConfiguration

### ISSUE THREAD

**Issue by kbp1234** [harbby/sylph#95]
```
19-05-20 17:23:02 INFO[PipelinePluginLoader.java:126]-Find PipelinePlugin:ideal.sylph.plugins.kudu.KuduSink
19-05-20 17:23:02 INFO[PipelinePluginLoader.java:181]-loading RealTime Pipeline Plugin:class ideal.sylph.plugins.kudu.KuduSink ,the name is [kudu]
19-05-20 17:23:02 INFO[PipelinePluginLoader.java:126]-Find PipelinePlugin:ideal.sylph.plugins.mysql.PrintSink
19-05-20 17:23:02 INFO[PipelinePluginLoader.java:126]-Find PipelinePlugin:ideal.sylph.plugins.mysql.TestTrans
19-05-20 17:23:02 INFO[PipelinePluginLoader.java:126]-Find PipelinePlugin:ideal.sylph.plugins.mysql.MysqlAsyncJoin
19-05-20 17:23:02 INFO[PipelinePluginLoader.java:126]-Find PipelinePlugin:ideal.sylph.plugins.mysql.MysqlSink
19-05-20 17:23:02 INFO[PipelinePluginLoader.java:181]-loading RealTime Pipeline Plugin:class ideal.sylph.plugins.mysql.PrintSink ,the name is [console]
19-05-20 17:23:02 INFO[PipelinePluginLoader.java:181]-loading RealTime Pipeline Plugin:class ideal.sylph.plugins.mysql.TestTrans ,the name is [ideal.sylph.plugins.mysql.TestTrans]
19-05-20 17:23:02 INFO[PipelinePluginLoader.java:181]-loading RealTime Pipeline Plugin:class ideal.sylph.plugins.mysql.MysqlAsyncJoin ,the name is [mysql]
19-05-20 17:23:02 INFO[PipelinePluginLoader.java:181]-loading RealTime Pipeline Plugin:class ideal.sylph.plugins.mysql.MysqlSink ,the name is [mysql]
19-05-20 17:23:02 INFO[RunnerManager.java:106]-Found module dir directory modules/sylph-runner-flink Try to loading the runner
19-05-20 17:23:02 INFO[RunnerManager.java:113]-Installing runner ideal.sylph.runner.flink.FlinkRunner with dirideal.sylph.runner.flink.FlinkRunner@6a400542
19-05-20 17:23:02 INFO[RunnerManager.java:124]-Runner: ideal.sylph.runner.flink.FlinkRunner starts loading ideal.sylph.etl.PipelinePlugin
19-05-20 17:23:02 ERROR[SylphMaster.java:80]-SERVER START FAILED...
java.lang.NoClassDefFoundError: org/apache/hadoop/yarn/conf/YarnConfiguration
	at ideal.sylph.runtime.yarn.YarnModule.configure(YarnModule.java:42)
	at com.github.harbby.gadtry.ioc.BindMapping.create(BindMapping.java:158)
	at com.github.harbby.gadtry.ioc.IocFactory.create(IocFactory.java:55)
	at ideal.sylph.runner.flink.FlinkContainerFactory.<init>(FlinkContainerFactory.java:68)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at ideal.sylph.main.service.RunnerManager.lambda$createRunner$1(RunnerManager.java:129)
	at com.github.harbby.gadtry.base.Throwables.noCatch(Throwables.java:92)
	at ideal.sylph.main.service.RunnerManager.createRunner(RunnerManager.java:129)
	at ideal.sylph.main.service.RunnerManager.lambda$loadRunners$0(RunnerManager.java:114)
	at com.github.harbby.gadtry.classloader.PluginLoader$Builder.loadModule(PluginLoader.java:201)
	at com.github.harbby.gadtry.classloader.PluginLoader$Builder.build(PluginLoader.java:185)
	at ideal.sylph.main.service.RunnerManager.loadRunners(RunnerManager.java:117)
	at ideal.sylph.main.SylphMaster.main(SylphMaster.java:70)
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.yarn.conf.YarnConfiguration
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at com.github.harbby.gadtry.classloader.PluginClassLoader.loadClass(PluginClassLoader.java:83)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 17 more

```

**Comment by springdream12138** [comment]
Have you solved this problem?

**Comment by kbp1234** [comment]
已经解决了，谢谢，主要是缺包导致的

**Comment by kbp1234** [comment]
> Have you solved this problem?

已经解决了，谢谢，主要是缺包导致的

**Comment by i4late** [comment]
gradle配置有问题吗？下载新代码后也是报这样的问题

**Comment by qiuqingyu** [comment]
> > Have you solved this problem?
> 
> 已经解决了，谢谢，主要是缺包导致的

麻烦问下怎么解决的？

**Comment by godcvcv** [comment]
想问下是缺什么包导致的，谢谢

**Comment by JackrayWang** [comment]
怎么配置的？

**Comment by zhanjianS** [comment]
请问下是怎么解决的，我把hadoop的hadoop-yarn-api和hadoop-common导入到项目的lib下，并没有成功

**Comment by zhanjianS** [comment]
@godcvcv @JackrayWang @qiuqingyu 把hadoop的hadoop-yarn-api和hadoop-common hadoop-yarn-client 3个包放到flink的lib下，项目可以启动了
